const dives = [
  {
    date: "7/2/1990",
    depth: 6,
    duration: 20,
    site: "Coco beach",
    city: "Nice",
    country: "France",
    notes: "BE class",
  },
  {
    date: "7/3/1990",
    depth: 6,
    duration: 35,
    site: "Grotte a corail",
    city: "Nice",
    country: "France",
    notes: "BE class",
  },
  {
    date: "7/4/1990",
    depth: 7,
    duration: 45,
    site: "Plage de la Reserve",
    city: "Nice",
    country: "France",
    notes: "BE class",
  },
  {
    date: "7/5/1990",
    depth: 9,
    duration: 30,
    site: "Coco beach",
    city: "Nice",
    country: "France",
    notes: "BE class",
  },
  {
    date: "7/6/1990",
    depth: 13,
    duration: 25,
    site: "Grotte a corail",
    city: "Nice",
    country: "France",
    notes: "BE class",
  },
  {
    date: "7/12/1990",
    depth: 14,
    duration: 25,
    site: "Cavernes",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Scouts camp",
  },
  {
    date: "7/14/1990",
    depth: 11,
    duration: 35,
    site: "Aragon",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Scouts camp - photo shoot",
  },

  {
    date: "7/16/1990",
    depth: 10,
    duration: 30,
    site: "Les Jardins de Sausset",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Scouts camp",
  },
  {
    date: "7/17/1990",
    depth: 11,
    duration: 22,
    site: "Le petit Morna",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Scouts camp",
  },
  {
    date: "7/21/1990",
    depth: 16,
    duration: 35,
    site: "Les eceuils de Mejan",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Scouts camp",
  },
  {
    date: "7/23/1990",
    depth: 30,
    duration: 35,
    site: "Le petit Mejan",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Scouts camp",
  },
  {
    date: "7/24/1990",
    depth: 36,
    duration: 30,
    site: "Mejan",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Scouts camp",
  },
  {
    date: "7/24/1990",
    depth: 15,
    duration: 40,
    site: "La Vesse",
    city: "Sausset-les-Pins",
    country: "France",
    night: true,
    notes: "Scouts camp - night dive",
  },
  {
    date: "7/25/1990",
    depth: 30,
    duration: 30,
    site: "Epave du Chaouen",
    city: "Planier",
    country: "France",
    wreck: true,
    notes: "Scouts camp",
  },
  {
    date: "8/12/1990",
    depth: 42,
    duration: 25,
    site: "Mejan",
    city: "Sausset-les-Pins",
    country: "France",
    notes: "Deep dive",
  },
  {
    date: "11/8/1990",
    depth: 6,
    duration: 40,
    site: "Plage de la Reserve",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "11/10/1990",
    depth: 26,
    duration: 35,
    site: "Grotte a corail",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "11/10/1990",
    depth: 26,
    duration: 47,
    site: "L'ascenseur",
    city: "Nice",
    country: "France",
    notes: "Explo Monopalme",
  },
  {
    date: "11/15/1990",
    depth: 23,
    duration: 60,
    site: "Coco beach",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "11/17/1990",
    depth: 25,
    duration: 30,
    site: "Cap de Nice",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "11/17/1990",
    depth: 30,
    duration: 30,
    site: "Le Plateau",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },

  {
    date: "11/22/1990",
    depth: 22,
    duration: 31,
    site: "Grotte a corail",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "11/24/1990",
    depth: 24,
    duration: 35,
    site: "Meterling",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "11/29/1990",
    depth: 20,
    duration: 25,
    site: "Grotte a corail",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "4/14/1991",
    depth: 20,
    duration: 25,
    site: "St Jean",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "7/2/1991",
    depth: 25,
    duration: 30,
    site: "Meterling",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "7/11/1991",
    depth: 25,
    duration: 30,
    site: "Cap de Nice",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "7/13/1991",
    depth: 22,
    duration: 30,
    site: "Cap de Nice",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "9/5/1991",
    depth: 28,
    duration: 51,
    site: "Cap de Nice",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "9/10/1991",
    depth: 23,
    duration: 43,
    site: "Semaphore",
    city: "Nice",
    country: "France",
    notes: "1er Echelon class",
  },
  {
    date: "9/19/1991",
    depth: 40,
    duration: 40,
    site: "Semaphore",
    city: "Nice",
    country: "France",
    notes: "Deep dive",
  },

  {
    date: "7/14/1992",
    depth: 24,
    duration: 35,
    site: "L'interdite",
    city: "Nice",
    country: "France",
    notes: "Explo",
  },
  {
    date: "10/8/1992",
    depth: 30,
    duration: 30,
    site: "Sud Semaphore",
    city: "Nice",
    country: "France",
    notes: "Oxygene Campus Aqua Science",
  },
  {
    date: "7/19/1993",
    depth: 29,
    duration: 40,
    site: "Les Marches",
    city: "Nice",
    country: "France",
    notes: "Explo",
  },
  {
    date: "8/8/1993",
    depth: 10,
    duration: 40,
    site: "Le Plateau",
    city: "Nice",
    country: "France",
    notes: "Baptheme de Axelle et Amylyn",
  },
  {
    date: "9/10/1993",
    depth: 18,
    duration: 30,
    site: "Lanai second cathedrals",
    city: "Lahaina",
    state: "HI",
    country: "US",
    notes: "Explo",
  },
  {
    date: "9/10/1993",
    depth: 16,
    duration: 40,
    site: "Lanai knob's hill",
    city: "Lahaina",
    state: "HI",
    country: "US",
    notes: "Explo",
  },
  {
    date: "9/14/1993",
    depth: 16,
    duration: 40,
    site: "Molokini",
    city: "Lahaina",
    state: "HI",
    country: "US",
    notes: "Turtles",
  },
  {
    date: "8/13/1995",
    depth: 11,
    duration: 45,
    site: "Semaphore",
    city: "Nice",
    country: "France",
    notes: "Baptheme de Laura",
  },
  {
    date: "4/8/1996",
    depth: 13,
    duration: 33,
    site: "Coco beach",
    city: "Nice",
    country: "France",
    notes: "Explo",
  },
  {
    date: "7/29/2001",
    depth: 13,
    duration: 48,
    site: "Monterey",
    city: "Monterey",
    state: "CA",
    country: "US",
    temperature: 10.5,
    notes: "Kelp forest + crabs",
  },
  {
    date: "7/29/2001",
    depth: 13,
    duration: 59,
    site: "Monterey",
    city: "Monterey",
    state: "CA",
    country: "US",
    temperature: 10.5,
    notes: "Sun fish",
  },
  {
    date: "10/20/2001",
    depth: 33,
    duration: 35,
    site: "Yukon wreck",
    city: "San Diego",
    state: "CA",
    country: "US",
    wreck: true,
    notes: "Wreck dive",
  },
  {
    date: "3/2/2003",
    depth: 20,
    duration: 37,
    site: "US Liberty wreck",
    city: "Tulamben",
    state: "Bali",
    country: "Indonesia",
    wreck: true,
    notes: "Wreck dive",
  },
  {
    date: "3/2/2003",
    depth: 18,
    duration: 42,
    site: "Tulamben",
    city: "Tulamben",
    state: "Bali",
    country: "Indonesia",
    notes: "Explo",
  },
  {
    date: "6/29/2025",
    depth: 20,
    duration: 20,
    site: "Blue hole",
    city: "Naples",
    state: "FL",
    country: "US",
    nitrox: 31,
    temperature: 30,
    notes: "Advanced Open Water class",
  },
  {
    date: "6/29/2025",
    depth: 12.5,
    duration: 20,
    site: "Reef",
    city: "Naples",
    state: "FL",
    country: "US",
    nitrox: 32,
    temperature: 30,
    notes: "Advanced Open Water class",
  },
  {
    date: "7/1/2025",
    depth: 10,
    duration: 20,
    site: "Lake Denton",
    state: "FL",
    country: "US",
    temperature: 30,
    notes: "Advanced Open Water class",
  },
  {
    date: "7/1/2025",
    depth: 10,
    duration: 20,
    site: "Lake Denton",
    state: "FL",
    country: "US",
    temperature: 30,
    notes: "Advanced Open Water class",
  },
  {
    date: "7/1/2025",
    depth: 10,
    duration: 20,
    site: "Lake Denton",
    state: "FL",
    country: "US",
    temperature: 30,
    notes: "Explo",
  },

  {
    date: "9/15/2025",
    depth: 4,
    duration: 42,
    site: "La Jolla Shores - Marine room",
    city: "San Diego",
    state: "CA",
    country: "US",
    temperature: 21,
    notes: "Horn shark",
  },
  {
    date: "9/15/2025",
    depth: 18,
    duration: 43,
    site: "La Jolla Shores - Scripps canyon",
    city: "San Diego",
    state: "CA",
    country: "US",
    temperature: 17,
    notes: "Flunder + lobsters + box jellyfish",
  },
  {
    date: "9/16/2025",
    depth: 9,
    duration: 60,
    site: "La Jolla Cove - Swim platform",
    city: "San Diego",
    state: "CA",
    country: "US",
    temperature: 19.4,
    notes: "School of sharks + sea lions + albatross",
  },
  {
    date: "9/16/2025",
    depth: 9,
    duration: 65,
    site: "La Jolla Cove - North side",
    city: "San Diego",
    state: "CA",
    country: "US",
    temperature: 21.6,
    notes: "Sea lions",
  },
  {
    date: "9/17/2025",
    depth: 7.5,
    duration: 36,
    site: "La Jolla Cove - C cave",
    city: "San Diego",
    state: "CA",
    country: "US",
    temperature: 18.3,
    notes: "Sea lions + cave",
  },

  {
    date: "9/17/2025",
    depth: 11,
    duration: 42,
    site: "La Jolla Cove - West side",
    city: "San Diego",
    state: "CA",
    country: "US",
    temperature: 16.7,
    notes: "Kelp forest + lobsters + parrot fish",
  },

  {
    date: "11/30/2025",
    depth: 8,
    duration: 15,
    site: "Key Largo",
    city: "Key Largo",
    state: "FL",
    country: "US",
    nitrox: 32,
    temperature: 26.7,
    notes: "Aborted dive",
  },
  {
    date: "12/1/2025",
    depth: 15.4,
    duration: 47,
    site: "Benwood wreck",
    city: "Key Largo",
    state: "FL",
    country: "US",
    nitrox: 31,
    wreck: true,
    temperature: 26.7,
    notes: "Turtles + shark",
  },
  {
    date: "12/1/2025",
    depth: 12.5,
    duration: 48,
    site: "French reef",
    city: "Key Largo",
    state: "FL",
    country: "US",
    nitrox: 32,
    temperature: 26.7,
    notes: "Explo",
  },
];
